### ISSUE TITLE
Run Loki in CI

### ISSUE THREAD

**Issue by 72636c** [seek-oss/scoobie#4]
We’ve found that running Loki against a static Storybook render leads to significant flakiness.

There are probably two options here:

- Try to figure out the root cause (seemingly Loki not waiting for the page to properly load) and contribute an upstream patch
- Get the live Storybook server running in a separate Docker Compose container, and run Loki against that container

**Comment by 72636c** [comment]
Old Buildkite config:

```yaml
steps:
  - commands:
      - yarn build-storybook
      - yarn test:loki:ci
    plugins:
      - docker#v3.5.0:
          environment:
            - BUILDKITE_BUILD_PATH=/var/lib/buildkite/builds
          propagate-environment: true
          volumes:
            - /usr/local/bin/buildkite-agent:/usr/local/bin/buildkite-agent
            - /var/lib/buildkite/builds:/var/lib/buildkite/builds
            - /var/run/docker.sock:/var/run/docker.sock
            - /workdir/dist-storybook-tmp:/workdir/dist-storybook-tmp
            - /workdir/node_modules
```
